blacklist:
  names: admin,administrator,root
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: candidate
    password: java
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true                   